# Numpy

1. Arrays - 1D, 2D, 3D, etc.
2. Numpy over Lists - Numpy is faster because Numpy uses fixed types.

## Applications of Numpy
1. Mathematics (MATLAB Replacement)
2. SciPy has even more functionalities for mathematics.
3. Backend (Pandas, Connect4, Digital Photography).
4. Machine Learning

In [2]:
import numpy as np

### Basics

In [4]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [5]:
b = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(b)

[[1 2 3 4 5]
 [6 7 8 9 0]]


### Dimension
**ndim** -> Gets the number dimension of the array.

### Shape
**shape** -> Tells the (Rows, Columns) of an array.

### Data Type 
**dtype** -> Tells the data type of a variable.


In [7]:
print(a.ndim)
print(b.ndim)

1
2


In [8]:
print(a.shape)
print(b.shape)

(3,)
(2, 5)


In [9]:
a.dtype

dtype('int16')

In [10]:
b.dtype

dtype('int64')

## Accessing/Changing Specific Elements, Rows, Columns, etc.

In [12]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# Get a specific element [r, c]
a[1,5]

13

In [14]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [16]:
# Getting a little more fancy [startindex:endindex:stepwise]
a[0,1:6:2]

array([2, 4, 6])

In [17]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


### Initializing Different Types of Arrays

In [19]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# All 1s matrix
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [21]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [22]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.67323039, 0.03361091],
       [0.27870502, 0.77620166],
       [0.2914281 , 0.64106659],
       [0.62458804, 0.101424  ]])

In [23]:
np.random.random_sample(a.shape)

array([[0.27594492, 0.23261862, 0.77906528, 0.50155068, 0.79233255,
        0.63638376, 0.46129152],
       [0.96632162, 0.80412642, 0.3196629 , 0.87663792, 0.15619845,
        0.47160125, 0.93732968]])

In [24]:
# Random Integer values
np.random.randint(4,7, size = (3,3))

array([[6, 5, 5],
       [4, 5, 4],
       [6, 6, 4]])

In [25]:
# Identity Matrix (Square matrix of 0s and 1s)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [27]:
c = np.zeros((5,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
c[0,:] = 1
c[-1,:] = 1
c[:,0] = 1
c[:,-1] = 1
c[2:2] = 9

In [29]:
print(c)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays!!!

In [31]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(b)

[100   2   3]


In [32]:
print(a)

[100   2   3]


In [33]:
c = np.array([1,2,3])
d = c.copy()
d[0] = 100

print(d)

[100   2   3]


In [34]:
print(c)

[1 2 3]


### Mathematics

In [36]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [37]:
a + 2

array([3, 4, 5])

In [38]:
a - 2

array([-1,  0,  1])

In [39]:
a/2

array([0.5, 1. , 1.5])

In [40]:
a*2

array([2, 4, 6])

In [41]:
a**2

array([1, 4, 9])

In [42]:
# Take the sin
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

### Linear Algebra

In [44]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [45]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [46]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [47]:
# Find the determinant
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
np.linalg.det(c)

1.0

In [49]:
d = np.full((4,4),5)
print(d)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [50]:
np.linalg.det(d)

0.0

### Statistics

In [52]:
stats = np.array([[1,2,3],[4,5,6],[7,8,9]])
stats

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.min(stats)

1

In [54]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [55]:
np.min(stats, axis = 1)

array([1, 4, 7])

In [56]:
np.max(stats)

9

In [57]:
np.max(stats, axis = 0)

array([7, 8, 9])

In [58]:
np.max(stats, axis = 1)

array([3, 6, 9])

### Reorganizing Arrays

In [60]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [61]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [62]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [63]:
v2 = np.array([5,6,7,8])
print(v2)

[5 6 7 8]


In [64]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
# Horizontal stacking vectors
h1 = np.ones((2,4))
print(h1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [66]:
h2 = np.zeros((2,2))
print(h2)

[[0. 0.]
 [0. 0.]]


In [67]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Load Data from File

In [69]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

#### Boolean Masking and Advanced Indexing

In [71]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [72]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [73]:
#### You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [74]:
# This code tells you if there are numbers greater than 50 in each column.
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [75]:
# This code tells you if there are numbers greater than 50 in each row.
np.any(filedata > 50, axis = 1)

array([ True,  True,  True])

In [76]:
# This code tells you if there are numbers greater than 50 in the whole array.
np.any(filedata > 50)

True

In [77]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [78]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [79]:
a = np.arange(1,31,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [80]:
b = a.reshape((6,5))
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [81]:
for i in range(min(b.shape[0]-1,b.shape[1]-1)):
    print(b[i,i+1])

2
8
14
20
